[package]
name = "gwilight_model"
authors = [ "The HarTex Community" ]
description = """
Guilded API models for the Gwilight ecosystem of crates.
"""
edition = "2021"
license = "ISC"
repository = "https://github.com/HarTexTeam/gwilight"
rust-version = "1.57.0"
version = "0.1.0"

[dependencies]
uuid = { default-features = false, features = [ "v5" ], version = "0.8.2" }
time = { default-features = false, features = [ "parsing", "std" ], version = "0.3.5" }
