[package]
name = "guilded_http"
authors = [ "The HarTex Community" ]
description = """
Guilded API HTTP Client for the Guilded-rs ecosystem of crates.
"""
edition = "2021"
license = "ISC"
repository = "https://github.com/HarTexTeam/guilded-rs"
rust-version = "1.57.0"
version = "0.1.0-dev.1"

[dependencies]
